import Head from "next/head";

import Hero from "../components/HeroSection/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero title="jeg er ikke google premium partner, fordi jeg ikke arbejder for google jeg arbejder for jer" />
    </>
  );
}
